<section class="Footer" id="ProductosCotizar">
  <div class="col-xs-12 nopadding">
    <div class="row">
        <div class="col-xs-12 nopadding">
          <div class="col-xs-6 nopadding">
            <div class="col-xs-12 nopadding container1 text-center">
              <div class="col-xs-12 vertical">
                <h4 class="col-xs-12 nopadding text-center textWhite bold text-uppercase">METODOS DE PAGO</h4>
                <div class="col-xs-12 text-center nopadding">
                  <div class="col-xs-12 centered" style="width: auto;">
                    <a href="#" class="textWhite icon">
                      <i class="fa fa-credit-card-alt" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon">
                      <i class="fa fa-cc-visa" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon">
                      <i class="fa fa-cc-mastercard" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon">
                      <i class="fa fa-cc-diners-club" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon">
                      <i class="fa fa-cc-paypal" aria-hidden="true"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xs-12 nopadding container2 text-center">
              <div class="col-xs-12 vertical">
                <h4 class="col-xs-12 nopadding text-center textWhite bold text-uppercase">Encuentranos tambien en:</h4>
                <div class="col-xs-12 text-center nopadding">
                  <div class="col-xs-12 centered" style="width: auto;">
                    <a href="#" class="textWhite icon2">
                      <i class="fa fa-facebook" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon2">
                      <i class="fa fa-twitter" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon2">
                      <i class="fa fa-google-plus" aria-hidden="true"></i>
                    </a>
                    <a href="#" class="textWhite icon2">
                      <i class="fa fa-instagram" aria-hidden="true"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xs-6 container3 nopadding">
            <div class="col-xs-12 vertical text-center">
              <div class="col-xs-12 text-center">
                <img class="col-xs-10 col-md-6 vpadding nopaddingTop centered" src="assets/img/logo.png" alt="">
                <h4 class="textWhite vxpadding nopaddingTop thin">Av. Marginal 603 Urb. Javier Prado Oeste</h4>
              </div>
              <div class="col-xs-12 text-center">
                <a href="#"><h5 class="textWhite thin">NOSOTROS</h5></a>
                <a href="#"><h5 class="textWhite thin">CONTACTENOS</h5></a>
                <a href="#"><h5 class="textWhite thin">TERMINOS Y CONDICIONES</h5></a>
                <a href="#"><h5 class="textWhite thin">SEGURIDAD Y PRIVACIDAD</h5></a>
                <a href="#"><h5 class="textWhite thin">TRABAJA CON NOSOTROS</h5></a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xs-12 copyright text-center vpadding">
          <h5 class="nomargin">2017 INNOVALED PERU S.A.C. | Todos los derechos reservados</h5>
        </div>
    </div>
  </div>
</section>



<div class="modal fade" id="carritoModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="assets/img/close.svg"></button>
        <h4 class="modal-title textGrey" id="textTittle">Carrito de compras: <strong></strong></h4>
      </div>
      <div class="modal-body">
        <div class="row">
          	<div class="col-xs-12 nopadding text-center">
  				<ul class="nav nav-tabs" role="tablist">
  			  		<li role="presentation" class="active">
  			  			<a href="#cart" aria-controls="cart" role="tab" data-toggle="tab">1. Carrito</a>
  			  		</li>
  			  		<li role="presentation">
  			  			<a href="#quote" aria-controls="quote" role="tab" data-toggle="tab">2. Cotizar y enviar</a>
  			  		</li>
  				</ul>
  				<div class="tab-content">
  				  	<div role="tabpanel" class="tab-pane active" id="cart">
  				  		<div class="col-xs-12 nopadding" id='carrito'>
							<table class="table table-bordered">
								<thead>
									<tr>
										<th>#</th>
										<th>Producto</th>
										<th>Cantidad</th>
										<th>Precio</th>
										<th>Importe</th>
										<th>Eliminar</th>
									</tr>
								</thead>
								<tbody>

								</tbody>
							</table>
  				  		</div>
  				  	</div>
  				  	<div role="tabpanel" class="tab-pane" id="quote">
  				  		<form id="formCotizar" class="col-xs-12 noHorizontalPadding vxpadding">
                    <div class="col-xs-12 col-sm-6 form-group"> 
                        <label class="sr-only" for="exampleInputAmount">Nombre</label> 
                        <div class="input-group"> 
                            <div class="input-group-addon">Nombre</div> 
                            <input class="form-control" id="nombre" name="nombre" placeholder="Nombre"> 
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-6 form-group"> 
                        <label class="sr-only" for="exampleInputAmount">Correo</label> 
                        <div class="input-group"> 
                            <div class="input-group-addon">Correo</div> 
                            <input class="form-control group" id="correo" name="correo" placeholder="Correo"> 
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-6 form-group"> 
                        <label class="sr-only" for="exampleInputAmount">Telefono</label> 
                        <div class="input-group"> 
                            <div class="input-group-addon">Telefono</div> 
                            <input class="form-control group" id="telefono" name="telefono" placeholder="Telefono"> 
                        </div> 
                    </div>
                    <div class="col-xs-12 col-sm-6 form-group"> 
                        <label class="sr-only" for="exampleInputAmount">Empresa</label> 
                        <div class="input-group"> 
                            <div class="input-group-addon">Empresa</div> 
                            <input class="form-control" id="empresa" name="empresa" placeholder="Empresa"> 
                        </div> 
                    </div>
                    <div class="col-xs-12 form-group"> 
                        <label class="sr-only" for="exampleInputAmount">Observaciones</label> 
                        <div class="input-group"> 
                            <div class="input-group-addon">Observaciones</div>
                            <textarea class="form-control" name="observaciones" id="observaciones" rows="5" placeholder="Observaciones"></textarea>
                        </div> 
                    </div>
                </form>
                <div class="col-xs-12">
                  <a href="#" class="btn1 pull-right" id="btnCotizar">COTIZAR</a>
                </div>
  				  	</div>
  				</div>
          	</div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

<!-- Latest compiled and minified JavaScript -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/scrollReveal.js/3.3.6/scrollreveal.min.js"></script>
<script src='assets/js/pnotify.custom.min.js'></script>
<script src='assets/js/parallax.min.js'></script>
<script src='assets/js/slick.js'></script>
<script src='assets/js/dev.js'></script>
<script src='assets/js/productos.js'></script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAYkMddFBx2DO9pgrHW3PG1-bT5D4_V-WE"></script>
<script src='assets/js/contacto.js'></script>
<script src='assets/js/carrito.js'></script>
<script src="assets/js/Menu.js"></script>
<?php if(isset($this->js)) echo $this->js; ?>
</html>