
<div class="modal fade" id="carrito" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><img src="assets/img/close.svg"></button>
        <h4 class="modal-title textGrey" id="textTittle">Carrito de compras: <strong></strong></h4>
      </div>
      <div class="modal-body">
        <div class="row">
          	<div class="col-xs-12 nopadding text-center">
  				<ul class="nav nav-tabs" role="tablist">
  			  		<li role="presentation" class="active">
  			  			<a href="#cart" aria-controls="cart" role="tab" data-toggle="tab">Carrito</a>
  			  		</li>
  			  		<li role="presentation">
  			  			<a href="#quote" aria-controls="quote" role="tab" data-toggle="tab">Cotizar</a>
  			  		</li>
  				</ul>
  				<div class="tab-content">
  				  <div role="tabpanel" class="tab-pane active" id="cart">
  				  	1
  				  </div>
  				  <div role="tabpanel" class="tab-pane" id="quote">
  				  	2
  				  </div>
  				</div>
          	</div>
        </div>
      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>
</body>

<!-- Latest compiled and minified JavaScript -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.16.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/scrollReveal.js/3.3.6/scrollreveal.min.js"></script>
<script src='assets/js/pnotify.custom.min.js'></script>
<script src='assets/js/parallax.min.js'></script>
<script src='assets/js/slick.js'></script>
<script src='assets/js/form.js'></script>
<script src='assets/js/dev.js'></script>
<script src='assets/js/productos.js'></script>
</html>