<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Handlee|Itim" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="assets/css/hamburgers.min.css">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="assets/css/pnotify.custom.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">	
	<link rel="stylesheet" href="assets/css/font.css">
	<link rel="stylesheet" href="assets/css/template.css">
	<link rel="stylesheet" href="assets/css/dev.css">
	<link href='assets/img/icon.png' rel='shortcut icon' type='image/png'>
	<title><?php if(isset($this->titulo)) echo $this->titulo; ?></title>
</head>
<body>

<div class="loaderPage">
	<div class="cSVG">
		<img src="assets/img/loader.svg" alt="">
	</div>
</div>

<div id="hamburgerMenu">
	<a href="#" class="scrollTo">
		<img src="assets/img/logo.png" class="logoMovile" alt="">
	</a>
	<div>
		<button class="hamburger hamburger--collapse" type="button">
		  <span class="hamburger-box">
		    <span class="hamburger-inner"></span>
		  </span>
		</button>
		<a href="#" class="search">
			<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 10.9 10.9" style="enable-background:new 0 0 10.9 10.9;" xml:space="preserve">
				<path class="st0" d="M8.3,1.4c-1.9-1.9-4.9-1.9-6.8,0s-1.9,4.9,0,6.8c1.7,1.7,4.4,1.9,6.2,0.5l2.2,2.2l1.1-1.1L8.7,7.7C10.1,5.8,10,3.1,8.3,1.4z M7,7C5.8,8.2,3.9,8.2,2.7,7s-1.2-3.1,0-4.3s3.1-1.2,4.3,0S8.2,5.8,7,7z"/>
			</svg>
		</a>
	</div>
</div>

<div id="menu">
	<div class="vertical">
		<div class="col-xs-12 nopadding text-center">
			<ul class="centered">
				<li class="carrito">
					<a href="#" data-toggle="modal" data-target="#carrito">
						<svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 94.9 87.2" style="enable-background:new 0 0 94.9 87.2;" xml:space="preserve">
							<g>
								<path d="M94.2,14.2c-0.6-0.8-1.5-1.2-2.5-1.2H23.5L21.2,2.5C20.9,1,19.6,0,18.1,0H3.2C1.4,0,0,1.4,0,3.2s1.4,3.2,3.2,3.2h12.4l13,59.4c0.3,1.5,1.6,2.5,3.1,2.5h50.5c1.8,0,3.2-1.4,3.2-3.2s-1.4-3.2-3.2-3.2H34.3l-1.6-7.3h51.1c1.5,0,2.8-1,3.1-2.5l8-35.2C95,16,94.8,15,94.2,14.2z"/>
								<circle cx="75.6" cy="79.6" r="7.6"/>
								<circle cx="38.5" cy="79.6" r="7.6"/>
							</g>
						</svg>
					</a>
				</li>
				<li class=""><a class="active" href="#Home">Home</a></li>
				<li class=""><a class="" href="#Productos">Productos</a></li>
				<li class=""><a class="" href="#ClientesMarcasPartners">Nosotros</a></li>
				<li class=""><a class="" href="#Servicios_1">Servicios</a></li>
				<li class=""><a class="" href="#proyectos">Proyectos</a></li>
				<li class=""><a class="" href="#Marcas">Marcas</a></li>
			</ul>
		</div>
	</div>
</div>
