<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,300i,400,400i,500,500i,700,700i" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Handlee|Itim" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	<link rel="stylesheet" href="assets/css/hamburgers.min.css">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="assets/css/pnotify.custom.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">	
	<link rel="stylesheet" href="assets/css/font.css">
	<link rel="stylesheet" href="assets/css/inputs.css">
	<link rel="stylesheet" href="assets/css/template.css">
	<link rel="stylesheet" href="assets/css/dev.css">
	<link href='assets/img/icon.png' rel='shortcut icon' type='image/png'>
	<title><?php if(isset($this->titulo)) echo $this->titulo; ?></title>
</head>
<body>

<div class="loaderPage">
	<div class="cSVG">
		<img src="assets/img/loader.svg" alt="">
	</div>
</div>

<a href="index" class="logo">
	<img src="assets/img/logo_white.svg" alt="">
</a>

<?php if (isset($this->productos)): ?>
<div id="Menu" class="fixed">
	<div>
		<div class="col-xs-12 text-center containerLogo">
			<div class="col-xs-3 text-center nopadding">
				<button class="hamburger hamburger--slider" type="button">
				  	<span class="hamburger-box">
				  	  	<span class="hamburger-inner"></span>
				  	</span>
				</button>
			</div>
			<div class="col-xs-9 logoContent">
				<img src="assets/img/logo_grey.png" alt="" class="col-xs-12 pull-right">
			</div>
		</div>
		<div class="col-xs-12 containerOptions">
			<ul>
				<li><a class="directLink" href="index#Home">HOME</a></li>
				<li><a class="directLink" href="index#Empresas">CLIENTES</a></li>
				<li><a class="directLink" href="index#proyectos">PROYECTOS</a></li>
				<li><a class="directLink" href="index#Servicios_1">SERVICIOS</a></li>
				<li><a class="active">PRODUCTOS</a></li>
				<li><a class="directLink" href="index#contacto">CONTACTENOS</a></li>
			</ul>
		</div>
		<div class="col-xs-12 containerContact">
			<div class="col-xs-7">
				<a href="#">ventas@innovaled.pe</a>
			</div>
			<div class="col-xs-5">
				<a href="#">01 393 4964</a>
			</div>
		</div>
		<a href="#" class="col-xs-12 text-center containerSession">
			<img src="assets/img/cart_btn.svg" alt="">
			<span>CARRITO</span>
		</a>
	</div>
</div>
<?php else: ?>
<div id="Menu" class="fixed">
	<div>
		<div class="col-xs-12 text-center containerLogo">
			<div class="col-xs-3 text-center nopadding">
				<button class="hamburger hamburger--slider" type="button">
				  	<span class="hamburger-box">
				  	  	<span class="hamburger-inner"></span>
				  	</span>
				</button>
			</div>
			<div class="col-xs-9 logoContent">
				<img src="assets/img/logo_grey.png" alt="" class="col-xs-12 pull-right">
			</div>
		</div>
		<div class="col-xs-12 containerOptions">
			<ul>
				<li><a class="home" href="#Home">HOME</a></li>
				<li><a class="clientes" href="#Empresas">CLIENTES</a></li>
				<li><a class="proyectos" href="#proyectos">PROYECTOS</a></li>
				<li><a class="servicios" href="#Servicios_1">SERVICIOS</a></li>
				<li><a class="directLink" href="productos">PRODUCTOS</a></li>
				<li><a class="contactenos" href="#contacto">CONTACTENOS</a></li>
			</ul>
		</div>
		<div class="col-xs-12 containerContact">
			<div class="col-xs-7">
				<a href="#">ventas@innovaled.pe</a>
			</div>
			<div class="col-xs-5">
				<a href="#">01 393 4964</a>
			</div>
		</div>
		<a href="#" class="col-xs-12 text-center containerSession">
			<img src="assets/img/cart_btn.svg" alt="">
			<span>CARRITO</span>
		</a>
	</div>
</div>
<?php endif ?>
