<section id="Home">
	<div class="col-xs-12 nopadding slide slideEspecialistas" style="background-image: url('assets/img/img_1.jpg');">
		<div class="vertical backImage" data-animation="fadeInUpBig" data-delay="0.5s" style="background-image: url('assets/img/img_2.svg');"></div>
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 nopadding text-left">
							<h1 class="extra-bold vpadding textWhite lined" data-animation="fadeInLeft" data-delay="1s">Especialistas en Calidad,
							<br>Eficiencia y ahorro.</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideExperiencia" style="background-image: url('assets/img/img_3.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_4.svg');"></div>
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-left">
							<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
								<img src="assets/img/img_5.png" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 100px;">
							</div>
							<h2 class="extra-bold vpadding textWhite lined" data-animation="fadeInRight" data-delay="1s">5 años de experiencia brindando soluciones en tecnología LED</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideAniosRealizando" style="background-image: url('assets/img/img_18.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_17.svg');"></div>
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-left">
							<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
								<img src="assets/img/img_19.svg" alt="" class="col-xs-12 centered" data-animation="fadeInDownBig" data-delay="0.5s" style="width: 140px;">
							</div>
							<h2 class="extra-bold vpadding textWhite lined" data-animation="fadeInRight" data-delay="1s">2 años realizando proyectos de digital signage</h2>
						</div>
						<div class="col-xs-12 col-sm-7 nopadding text-center">
							<img src="assets/img/img_20.png" alt="" class="col-xs-12 centered img20" data-animation="fadeInRight" data-delay="1s">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideProyectos1Anio" style="background-image: url('assets/img/img_32.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_31.svg');"></div>
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-left">
							<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
								<img src="assets/img/img_33.svg" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 150px;">
							</div>
							<h2 class="extra-bold vpadding textWhite lined" data-animation="fadeInRight" data-delay="1s">1 año en proyectos eficiencia energética residencial</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideInnovaled" style="background-image: url('assets/img/img_34.jpg');">
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding text-center">
						<div class="col-xs-12 nopadding text-center">
							<img src="assets/img/logo.png" alt="" class="col-xs-12 nopadding centered" style="width: 350px;">
						</div>
						<div class="col-xs-12 nopadding text-center">
							<h3 class="textWhite semi-bold" data-animation="fadeInRight" data-delay="1s">CALIDAD QUE ILUMINA</h3>
						</div>
						<div class="col-xs-12 nopadding text-center">
							<h4 class="textWhite regular" data-animation="fadeInRight" data-delay="1s">tu estilo de vida</h4>
						</div>
						<div class="col-xs-12 nopadding text-center">
							<a href="productos" class="btn1 centered" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="vertical bottom">
			<div class="col-xs-12 text-center backRed">
				<ul class="centered">
					<li>
						<img src="assets/img/icon_email.svg" alt="">
						<a href="#">Llámenos: (01) 393-4964</a>
					</li>
					<li>
						<img src="assets/img/icon_telephone.svg" alt="">
						<a href="#">Escríbenos: ventas@innovaled.pe</a>
					</li>
				</ul>
			</div>
		</div>
	</div>
</section>




<section id="Servicios_1">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_7.svg');"></div>
	<div class="vertical contentV">
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
					<h2 class="textWhite regular">SERVICIOS</h2>
				</div>
				<div class="col-xs-12 nopadding">
					<div class="col-xs-12 col-sm-3 tabs">
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="0" class="active">Venta e Instalación de Iluminarias LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="1">Programación y dimensionamiento de Sistema LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="2">Elaboración de proyectos de Iluminación LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="3">Venta e Instalación de Pantallas LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="4">Mantenimiento de Pantallas LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="5">Venta e Instalación de Kits Solares</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-9 containerTabs">
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_8.svg" alt="">
								<h3 class="textWhite regular">VENTA E INSTALACIÓN DE PRODUCTOS LED <small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_9.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_12.svg" alt="">
								<h3 class="textWhite regular">PROGRAMACIÓN Y DIMENSIONAMIENTO DE SISTEMA LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_31.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_13.svg" alt="">
								<h3 class="textWhite regular">ELABORACIÓN DE PROYECTOS DE ILUMINACIÓN LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_35.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_14.svg" alt="">
								<h3 class="textWhite regular">Venta e Instalación de Pantallas LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_36.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_15.svg" alt="">
								<h3 class="textWhite regular">Mantenimiento de Pantallas LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_37.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_16.svg" alt="">
								<h3 class="textWhite regular">Venta e Instalación de Kits Solares</h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_38.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="Empresas">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_21.svg');"></div>
	<div class="vertical contentV">
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 nopadding text-left">
						<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
							<div class="col-xs-12 col-sm-10 centered revealBottom">
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey active" slideTo="0">Marcas</a>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey" slideTo="1">Nuestros Clientes</a>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey" slideTo="2">Partners</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
							<div class="col-xs-12">
								<div class="col-xs-12 nopadding" id="slideMarcas">
									<div class="col-xs-12 nopadding itemContentTab marcas">
										<div class="col-xs-6 item text-center">
											<img src="assets/img/marcas/logo1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-6 item text-center">
											<img src="assets/img/marcas/logo2.png" alt="" class="revealBottom">
										</div>
										<div class="col-xs-12 noHorizontalPadding vxxpadding text-center">
											<img class="col-xs-12 nopadding centered revealBottom" src="assets/img/marcas/logo3.png" alt="" style="width: 220px;">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<div class="col-xs-12 noHorizontalPadding vpadding text-center">
												<p class="textGrey nopadding nomargin revealBottom">Certificaciones de nuestros productos:</p>
											</div>
											<div class="col-xs-12 nopadding text-center">
												<img src="assets/img/marcas/logo4.png" alt="" class="centered revealBottom" style="width: 200px;">
											</div>
										</div>									
									</div>
									<div class="col-xs-12 nopadding itemContentTab nuestrosClientes">
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo2.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo3.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo4.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo5.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo6.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo7.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo8.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo9.png" alt="">
											<div></div>
										</div>
									</div>
									<div class="col-xs-12 nopadding itemContentTab partners">
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/2.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/3.png" alt="">
										</div>
										<div class="col-xs-12 col-sm-6 item text-center">
											<img src="assets/img/partners/4.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-6 item text-center">
											<img src="assets/img/partners/5.png" alt="">
										</div>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="proyectos">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_22.svg');"></div>
	<div class="col-xs-12 nopadding">
		<div class="row nopadding nomargin text-center containerFullHeight">
			<div class="col-xs-12 col-sm-3 nopadding">
				<div class="vertical">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 text-center">
							<h3 class="textWhite semi-bold">PROYECTOS</h3>
						</div>
						<div class="col-xs-12 nopadding">
							<ul class="projectList">
								<li class="revealBottom">
									<a href="0" class="active">
										<img src="assets/img/img_23.svg" alt="">
										<span style="color: #ffbd3d;">Iluminación LED</span>
									</a>
								</li>
								<li class="revealBottom">
									<a href="1">
										<img src="assets/img/img_24.svg" alt="">
										<span style="color: #17e8ff;">Video wall</span>
									</a>
								</li>
								<li class="revealBottom">
									<a href="2">
										<img src="assets/img/img_25.svg" alt="">
										<span style="color: #b600e7;">Pantallas LED</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-9 nopadding content" id="slideProjects">
				<div class="col-xs-12 first slideItem">
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-5 backImg" style="background-image: url('assets/img/img26.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">SISTEMA ILUMINARIA</span>
						</a>
						<a href="#" class="col-xs-12 col-sm-7 backImg" style="background-image: url('assets/img/img27.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">PANTALLAS LED</span>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-5 backImg" style="background-image: url('assets/img/img28.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">VIDEO WALL</span>
						</a>
						<a href="#" class="col-xs-12 col-sm-7 backImg" style="background-image: url('assets/img/img29.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">MÓDULOS LED</span>
						</a>
					</div>
				</div>
				<div class="col-xs-12 video_wall slideItem">
					<div class="col-xs-12 nopadding" style="background-image: url('assets/img/img27.jpg');">
						<div class="vertical dark"></div>
						<img src="assets/img/view.svg" alt="" class="view">
						<span class="textWhite">VIDEO WALLS</span>
					</div>
				</div>
				<div class="col-xs-12 third slideItem">

				</div>
			</div>
		</div>
	</div>
</section>
