<section id="Home">
	<div class="col-xs-12 nopadding slide slideInnovaled" style="background-image: url('assets/img/img_34.jpg');">
		<div class="vertical contentV">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding text-center">
						<div class="col-xs-12 nopadding text-center">
							<img src="assets/img/logo.png" alt="" class="col-xs-12 nopadding centered" style="width: 350px;">
						</div>
						<div class="col-xs-12 nopadding text-center">
							<h3 class="textWhite semi-bold" data-animation="fadeInRight" data-delay="1s">CALIDAD QUE ILUMINA</h3>
						</div>
						<div class="col-xs-12 nopadding text-center">
							<h4 class="textWhite regular" data-animation="fadeInRight" data-delay="1s">tu estilo de vida</h4>
						</div>
						<div class="col-xs-12 nopadding text-center">
							<a href="productos" class="btn1 centered" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideProyectos1Anio" style="background-image: url('assets/img/img_32.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_31.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-center">
							<div class="col-xs-8 col-sm-12 nopadding centered text-left">
								<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
									<img src="assets/img/img_33.svg" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 150px;">
								</div>
								<h2 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInRight" data-delay="1s">1 año en proyectos eficiencia energética residencial</h2>
						<div class="col-xs-12 nopadding text-left">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideAniosRealizando" style="background-image: url('assets/img/img_18.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_17.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-center">
							<div class="col-xs-8 col-sm-12 nopadding centered text-left">
								<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
									<img src="assets/img/img_19.svg" alt="" class="col-xs-12 centered" data-animation="fadeInDownBig" data-delay="0.5s" style="width: 140px;">
								</div>
								<h2 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInRight" data-delay="1s">2 años realizando proyectos de digital signage</h2>
						<div class="col-xs-12 nopadding text-left">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideEspecialistas" style="background-image: url('assets/img/img_1.jpg');">
		<div class="vertical backImage" data-animation="fadeInUpBig" data-delay="0.5s" style="background-image: url('assets/img/img_2.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding text-center">
						<div class="col-xs-8 col-sm-12 nopadding centered">
							<div class="col-xs-12 nopadding text-left">
								<h1 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInLeft" data-delay="1s">Especialistas en Calidad,
								<br>Eficiencia y ahorro.</h1>
						<div class="col-xs-12 nopadding text-left">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideExperiencia" style="background-image: url('assets/img/img_3.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_4.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-center">
							<div class="col-xs-8 col-sm-12 nopadding centered text-left">
								<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
									<img src="assets/img/img_5.png" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 100px;">
								</div>
								<h2 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInRight" data-delay="1s">5 años de experiencia brindando soluciones en tecnología LED</h2>
						<div class="col-xs-12 nopadding text-left">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>




<section id="Servicios_1">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_7.svg');"></div>
	<div class="vertical contentV">
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
					<h2 class="textWhite regular">SERVICIOS</h2>
				</div>
				<div class="col-xs-12 nopadding">
					<div class="col-xs-12 col-sm-3 tabs">
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="0" class="active">Venta e Instalación de Iluminarias LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="1">Programación y dimensionamiento de Sistema LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="2">Elaboración de proyectos de Iluminación LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="3">Venta e Instalación de Pantallas LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="4">Mantenimiento de Pantallas LED</a>
						</div>
						<div class="col-xs-12 revealBottom">
							<a href="#" slideTo="5">Venta e Instalación de Kits Solares</a>
						</div>
					</div>
					<div class="col-xs-12 col-sm-9 containerTabs">
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_8.svg" alt="">
								<h3 class="textWhite regular">VENTA E INSTALACIÓN DE PRODUCTOS LED <small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_9.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_12.svg" alt="">
								<h3 class="textWhite regular">PROGRAMACIÓN Y DIMENSIONAMIENTO DE SISTEMA LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_31.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_13.svg" alt="">
								<h3 class="textWhite regular">ELABORACIÓN DE PROYECTOS DE ILUMINACIÓN LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_35.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_14.svg" alt="">
								<h3 class="textWhite regular">Venta e Instalación de Pantallas LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_36.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_15.svg" alt="">
								<h3 class="textWhite regular">Mantenimiento de Pantallas LED<small class="textWhite" style="font-weight: 100;"><br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius ex corporis, accusamus consectetur aspernatur.</small></h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_37.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
						<div class="col-xs-12 tabed">
							<div class="col-xs-12 tittle">
								<img src="assets/img/img_16.svg" alt="">
								<h3 class="textWhite regular">Venta e Instalación de Kits Solares</h3>
							</div>
							<div class="col-xs-12 nopadding">
								<img src="assets/img/img_38.jpg" alt="" class="col-xs-12 noHorizontalPadding vpadding nopaddingTop">
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="Empresas">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_21.svg');"></div>
	<div class="vertical contentV">
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 nopadding text-left">
						<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
							<div class="col-xs-12 col-sm-10 centered revealBottom">
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey active" slideTo="0">Marcas</a>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey" slideTo="1">Nuestros Clientes</a>
										</div>
									</div>
								</div>
								<div class="col-xs-12 col-sm-4 nopadding text-center tabBrand revealBottom">
									<div class="col-xs-12 nopadding centered">
										<div class="vertical">
											<a href="#" class="col-xs-12 nopadding text-center textGrey" slideTo="2">Partners</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
							<div class="col-xs-12">
								<div class="col-xs-12 nopadding" id="slideMarcas">
									<div class="col-xs-12 nopadding itemContentTab marcas">
										<div class="col-xs-6 item text-center">
											<img src="assets/img/marcas/logo1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-6 item text-center">
											<img src="assets/img/marcas/logo2.png" alt="" class="revealBottom">
										</div>
										<div class="col-xs-12 noHorizontalPadding vxxpadding text-center">
											<img class="col-xs-12 nopadding centered revealBottom" src="assets/img/marcas/logo3.png" alt="" style="width: 220px;">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<div class="col-xs-12 noHorizontalPadding vpadding text-center">
												<p class="textGrey nopadding nomargin revealBottom">Certificaciones de nuestros productos:</p>
											</div>
											<div class="col-xs-12 nopadding text-center">
												<img src="assets/img/marcas/logo4.png" alt="" class="centered revealBottom" style="width: 200px;">
											</div>
										</div>									
									</div>
									<div class="col-xs-12 nopadding itemContentTab nuestrosClientes">
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo2.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo3.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo4.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo5.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo6.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo7.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo8.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/clientes/logo9.png" alt="">
											<div></div>
										</div>
									</div>
									<div class="col-xs-12 nopadding itemContentTab partners">
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/1.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/2.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-4 item text-center">
											<img src="assets/img/partners/3.png" alt="">
										</div>
										<div class="col-xs-12 col-sm-6 item text-center">
											<img src="assets/img/partners/4.png" alt="">
											<div></div>
										</div>
										<div class="col-xs-12 col-sm-6 item text-center">
											<img src="assets/img/partners/5.png" alt="">
										</div>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="proyectos">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_22.svg');"></div>
	<div class="col-xs-12 nopadding">
		<div class="row nopadding nomargin text-center containerFullHeight">
			<div class="col-xs-12 col-sm-3 nopadding">
				<div class="vertical">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 text-center">
							<h3 class="textWhite semi-bold">PROYECTOS</h3>
						</div>
						<div class="col-xs-12 nopadding">
							<ul class="projectList">
								<li class="revealBottom">
									<a href="0" class="active">
										<img src="assets/img/img_23.svg" alt="">
										<span style="color: #ffbd3d;">Iluminación LED</span>
									</a>
								</li>
								<li class="revealBottom">
									<a href="1">
										<img src="assets/img/img_24.svg" alt="">
										<span style="color: #17e8ff;">Video wall</span>
									</a>
								</li>
								<li class="revealBottom">
									<a href="2">
										<img src="assets/img/img_25.svg" alt="">
										<span style="color: #b600e7;">Pantallas LED</span>
									</a>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-9 nopadding content" id="slideProjects">
				<div class="col-xs-12 iluminacion_led slideItem">
					<div class="col-xs-12 nopadding">
						<a href="paneles_led" class="col-xs-12 col-sm-5 backImg" style="background-image: url('assets/img/img26.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">PANELES LED</span>
						</a>
						<a href="reflectores_led" class="col-xs-12 col-sm-7 backImg" style="background-image: url('assets/img/img28.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">REFLECTORES LED</span>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="cintas_led" class="col-xs-12 col-sm-5 backImg" style="background-image: url('assets/img/img_39.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">CINTAS LED</span>
						</a>
						<a href="modulos_led" class="col-xs-12 col-sm-7 backImg" style="background-image: url('assets/img/img_40.jpg');">
							<div class="vertical dark"></div>
							<img src="assets/img/view.svg" alt="" class="view">
							<span class="textWhite">MÓDULOS LED</span>
						</a>
					</div>
				</div>
				<div class="col-xs-12 video_wall slideItem">
					<a href="video_wall_proyectos" class="col-xs-12 backImg" style="background-image: url('assets/img/img_41.jpg');">
						<div class="vertical dark"></div>
						<img src="assets/img/view.svg" alt="" class="view">
						<span class="textWhite">VIDEO WALLS</span>
					</a>
				</div>
				<div class="col-xs-12 pantallas_led slideItem">
					<a href="indoor_1" class="col-xs-6 backImg" style="background-image: url('assets/img/img_42.jpg');">
						<div class="vertical dark"></div>
						<img src="assets/img/view.svg" alt="" class="view">
						<span class="textWhite">INDOOR</span>
					</a>
					<a href="outdoor_1" class="col-xs-6 backImg" style="background-image: url('assets/img/img_43.jpg');">
						<div class="vertical dark"></div>
						<img src="assets/img/view.svg" alt="" class="view">
						<span class="textWhite">OUTDOOR</span>
					</a>
				</div>
				<div class="col-xs-12 paneles_led slideItem">
					<a href="#" class="col-xs-12 backImg" style="background-image: url('assets/img/img_44.jpg');">
						<div class="col-xs-12 col-sm-10 col-md-8 contentDark">
							<span class="textWhite">PANELES LED</span>
							<p class="textWhite thin">En este proyecto se instalaron 150 paneles LED. Se utilizaron las correctas medidas de seguridad para que nuestros productos preserven y puedan dar una mayor satisfacción con un consumo mucho más económico a las iluminarias tradicionales.</p>
						</div>
					</a>
				</div>
				<div class="col-xs-12 reflectores_led slideItem">
					<a href="#" class="col-xs-12 backImg" style="background-image: url('assets/img/img_45.jpg');">
						<div class="col-xs-12 col-sm-10 col-md-8 contentDark">
							<span class="textWhite">REFLECTORES LED</span>
							<p class="textWhite thin">En este proyecto se instalaron 32 reflectores LED para 4 canchas de grass sintetico en el distrito de los Olivos. Se utilizaron las correctas medidas de seguridad para que nuestros productos preserven y puedan dar una mayor satisfacción con un consumo mucho más económico a las iluminarias tradicionales.</p>
						</div>
					</a>
					<a href="#" class="col-xs-12 backImg" style="background-image: url('assets/img/img_46.jpg');">
						<div class="col-xs-12 col-sm-10 col-md-8 contentDark">
							<span class="textWhite">REFLECTORES LED</span>
							<p class="textWhite thin">Instalación de 50 reflectores LED para un almacen de 400mts cuadrados en el distrito de Chorrillos. Se utilizaron las correctas medidas de seguridad para que nuestros productos preserven y puedan dar una mayor satisfacción con un consumo mucho más económico a las iluminarias tradicionales.</p>
						</div>
					</a>
				</div>
				<div class="col-xs-12 cintas_led slideItem">
					<a href="#" class="col-xs-12 col-sm-6 backImg" style="background-image: url('assets/img/img_47.jpg');">
						<div class="col-xs-12 contentDark">
							<span class="textWhite">CINTAS LED - LATINA</span>
							<p class="textWhite thin">En este proyecto se instalaron 30 cintas led RGB más amplificadores  y controladores RGB.</p>
						</div>
					</a>
					<a href="#" class="col-xs-12 col-sm-6 backImg" style="background-image: url('assets/img/img_48.jpg');">
					</a>
				</div>
				<div class="col-xs-12 modulos_led slideItem">
					<a href="#" class="col-xs-12 backImg" style="background-image: url('assets/img/img_49.jpg');">
						<div class="vertical end">
							<div class="col-xs-12 vpadding">
								<div class="col-xs-12 col-sm-10 col-md-8 contentDark">
									<span class="textWhite">MÓDULOS LED</span>
									<p class="textWhite thin">En este proyecto se instalaron 500 unidades de módulos led de color rojo para letras corporeas de la marca H&M.</p>
								</div>
							</div>
						</div>
					</a>
				</div>
				<div class="col-xs-12 video_wall_proyectos slideItem">
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-6 backImg">
							<span class="textWhite">VIDEO WALL</span>
							<p class="textWhite">En este proyecto se instalaron un total de 17 pantallas LED en 3 proyectos para la empresa colchones FORLI en distintos Centros Comerciales. La primera se realizo en Mega Plaza donde se utilizaron 4 pantallas led de 1mt x 56cm, para Plaza Norte se utilizaron 9 pantallas led y para Mall Sur se utilizó 4 pantallas led, todas con las correctas medidas de seguridad para que nuestros productos preserven y puedan dar una mayor satisfacción con un consumo mucho más económico</p>
						</a>
						<a href="reflectores_led" class="col-xs-12 col-sm-6 backImg" style="background-image: url('assets/img/img_50.jpg');">
							<span class="textWhite">MEGA PLAZA</span>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="paneles_led" class="col-xs-12 col-sm-6 backImg" style="background-image: url('assets/img/img_51.jpg');">
							<span class="textWhite">PLAZA NORTE</span>
						</a>
						<a href="reflectores_led" class="col-xs-12 col-sm-6 backImg" style="background-image: url('assets/img/img_52.jpg');">
							<span class="textWhite">MALL SUR</span>
						</a>
					</div>
				</div>
				<div class="col-xs-12 indoor_1 slideItem">
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_53.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Clarity Perú</span>
									<p class="textWhite thin">Pantalla LED rental con resolución P4.8 para un área de 50m2. Con el soporte de nuestro partner HUAHAI.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_54.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Parque Lambramani - C.C.</span>
									<p class="textWhite thin">Pantalla LED de 6mts x 3mts P10.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_55.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Wao Perú</span>
									<p class="textWhite thin">pantalla LED de 2.88mts x 1.92mts P10, con el soporte de nuestro parther HUAHAI.</p>
								</div>
							</div>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_56.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Assist Card</span>
									<p class="textWhite thin">Panel electrónico publicitario de 3.25mts x 37cm P10 color luz roja, con estructura metálica de 2.5cm.Av. Los Conquistadores 1136, San Isidro.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_57.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">EBCO</span>
									<p class="textWhite thin">Pantalla LED de 3mts x 2mts - P6 de 12 gabinetes LED para un área de 100m2. Patio de comidas en el Centro comercial de Arequipa.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_58.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Discoteca Viña del Mar</span>
									<p class="textWhite thin">Pantalla LED de 4mt x 2mt P6 para un área de 40m2. Chiclayo.</p>
								</div>
							</div>
						</a>
					</div>
					<span class="tittle">
						INDOOR
					</span>
				</div>
				<div class="col-xs-12 outdoor_1 slideItem">
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_59.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Cemento Pacasmayo</span>
									<p class="textWhite thin">Pantalla LED de 4mts x 3mts para un área de 12m2 con el soporte de nuestro partner HUAHAI. Pacasmayo.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_60.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Boticas Arcangel</span>
									<p class="textWhite thin">Pantalla LED de 5.12mts x 96cm P10.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_61.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Kartel</span>
									<p class="textWhite thin">Pantalla LED de 10mts x 5mts P16, con el soporte de nuestro partner HUAHAI. Pucallpa</p>
								</div>
							</div>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_62.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Publicidad & Eventos</span>
									<p class="textWhite thin">Pantalla LED de 2.88mts x 1.92mts P10 doble cara para un camión, con el soporte de nuestro partner HUAHAI</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_63.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Centro Óptica Iris</span>
									<p class="textWhite thin">En este proyecto se instalo una pantalla LED de 2mts x 2mts P6, con el soporte de nuestro partner HUAHAI. Camino Real - San Isidro.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_64.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Inkasur</span>
									<p class="textWhite thin">Pantallas LED de doble cara de 3.36mts x 2.24mts P10 para 3 camiones, con el soporte de nuestro partner HUAHAI.</p>
								</div>
							</div>
						</a>
					</div>
					<span class="tittle">
						OUTDOOR
					</span>
					<div class="next">
						<img src="assets/img/down.svg" alt="" index="outdoor_2">
					</div>
				</div>
				<div class="col-xs-12 outdoor_2 slideItem">
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_65.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Mini market - Maritza</span>
									<p class="textWhite thin">Panel electrónico LED de 2.16mts x 12cm. Calle las tres Marias en Monterrico</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_66.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Brapex</span>
									<p class="textWhite thin">Pantalla LED de 11.52mts x 5.76mts P20, con el soporte de nuestro partner HUAHAI</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_67.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Municipalidad de Chincha</span>
									<p class="textWhite thin">En este proyecto se instalo una pantalla LED de 2.88mts x 1.92mts P10 de doble cara. Chincha.</p>
								</div>
							</div>
						</a>
					</div>
					<div class="col-xs-12 nopadding">
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_68.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Latin American</span>
									<p class="textWhite thin">En este proyecto se instalo una pantalla LED de 5.76mts x 2.88mts P10, con el soporte de nuestro partner HUAHAI. Cerca de la Rambla de la Av. Brasil.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_69.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Tacna</span>
									<p class="textWhite thin">En este proyecto se instalo una pantalla LED de de 10.24mts x 5.12mts P16 en Tacna por el Ovalo Cuzco.</p>
								</div>
							</div>
						</a>
						<a href="#" class="col-xs-12 col-sm-4 backImg" style="background-image: url('assets/img/img_70.jpg');">
							<div class="vertical end">
								<div class="col-xs-12 contentDark">
									<span class="textWhite">Visual Capital</span>
									<p class="textWhite thin">Pantalla LED de 11.52mts x 5.76mts P20, con el soporte de nuestro partner HUAHAI. Cerca del aeropuerto Jorge Chávez - Callao.</p>
								</div>
							</div>
						</a>
					</div>
					<span class="tittle">
						OUTDOOR
					</span>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="contacto">
  <div class="container-fluid">
    <div class="row text-center">
      <div class="col-xs-12 nopadding">
		<div class="col-xs-12 col-sm-6 vheight">
			<div class="vertical" id="map"></div>
			<div class="vertical transparent">
				<div class="col-xs-12">
					<div class="col-xs-8 content text-left">
						<h3 class="col-xs-12 noHorizontalPadding nomargin vxpadding nopaddingTop extra-bold">CONTACTANOS</h3>
						<h4 class="col-xs-12 noHorizontalPadding nopaddingBottom nomargin vpadding bold">INNOVALED PERÚ S.A.C</h4>
						<p class="col-xs-12 noHorizontalPadding nomargin nopadding light">Av. Marginal 603 Urb. Javier Prado Este Salamanca de Monterrico, Lima – Perú</p>
						<h4 class="col-xs-12 noHorizontalPadding nopaddingBottom nomargin vpadding bold">CORREO</h4>
						<a href="mailto:contacto@innovaled.pe" class="col-xs-12 noHorizontalPadding nomargin nopadding light">contacto@innovaled.pe</a>
						<h4 class="col-xs-12 noHorizontalPadding nopaddingBottom nomargin vpadding bold">TÉLEFONO</h4>
						<a href="tel:0000000000" class="col-xs-12 noHorizontalPadding nomargin nopadding light">+51 1 393 4964</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6 vheight">
			<div class="vertical backWhite">
				<div class="col-xs-12 text-center">
					<form class="col-xs-12 col-sm-10 col-md-8 nopadding text-left" id="contacto">
						<div id="status">
							<div class="col-xs-12 nopadding vertical">
								<div class="col-xs-12 text-center">
									<img src="assets/img/loader.svg" class="col-xs-12 centered" style="width: 100px;">
									<h3 class="col-xs-12 text-center loading">Enviando</h3>
									<h3 class="col-xs-12 text-center success">Mensaje enviado <small>en breve nos pondremos contacto contigo.</small></h3>
									<h3 class="col-xs-12 text-center error">Ha ocurrido un error <small>intentelo mas tarde.</small></h3>
								</div>
							</div>
						</div>
						<div class="col-3 input-effect">
        					<input class="effect-21" type="text" placeholder="nombre" name="nombre" id="">
        				    <label>Nombre y apellidos *</label>
        				    <span class="focus-border">
        				    	<i></i>
        				    </span>
        				</div>
						<div class="col-3 input-effect">
        					<input class="effect-21" type="text" placeholder="correo" name="correo" id="">
        				    <label>Correo *</label>
        				    <span class="focus-border">
        				    	<i></i>
        				    </span>
        				</div>
						<div class="col-3 input-effect">
        					<input class="effect-21" type="text" placeholder="telefono" name="telefono" id="">
        				    <label>Telefono *</label>
        				    <span class="focus-border">
        				    	<i></i>
        				    </span>
        				</div>
						<div class="col-3 input-effect">
							<textarea name="mensaje" id="mensaje" rows="5" class="effect-21"></textarea>
        				    <label>Mensaje</label>
        				    <span class="focus-border">
        				    	<i></i>
        				    </span>
        				</div>
        				<div class="col-xs-12 nopadding">
							<a href="#" class="btn1 centered" data-animation="fadeInRight" data-delay="1s" id="btnEnviar">ENVIAR</a>
        				</div>
					</form>
				</div>
			</div>
		</div>
      </div>
    </div>
  </div>
</section>