<?php
/*
$link = mysql_connect('localhost', 'innovale_v2', 'cvk@8ojo9v1)') or die('No se pudo conectar: ' . mysql_error());
mysql_select_db('innovale_innovaled_v2') or die('No se pudo seleccionar la base de datos');
*/
$link = mysql_connect('localhost', 'root', '') or die('No se pudo conectar: ' . mysql_error());
mysql_select_db('innovaled_v2') or die('No se pudo seleccionar la base de datos');
$queryLineas = "SELECT * FROM linea ORDER BY IdLinea ASC";
$lineas = mysql_query($queryLineas) or die('Consulta fallida: ' . mysql_error());
$querySublineas = "SELECT * FROM sublinea ORDER BY IdLinea ASC";
$sublineas = mysql_query($querySublineas) or die('Consulta fallida: ' . mysql_error());
?>
<section id="Home">
	<div class="col-xs-12 nopadding slide slideProyectos1Anio" style="background-image: url('assets/img/img_32.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_31.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-center">
							<div class="col-xs-8 col-sm-12 nopadding centered text-left">
								<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
									<img src="assets/img/img_33.svg" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 150px;">
								</div>
								<h2 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInRight" data-delay="1s">1 año en proyectos eficiencia energética residencial</h2>
						<div class="col-xs-12 text-center">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideEspecialistas" style="background-image: url('assets/img/img_1.jpg');">
		<div class="vertical backImage" data-animation="fadeInUpBig" data-delay="0.5s" style="background-image: url('assets/img/img_2.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding text-center">
						<div class="col-xs-8 col-sm-12 nopadding centered">
							<div class="col-xs-12 nopadding text-left">
								<h1 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInLeft" data-delay="1s">Especialistas en Calidad,
								<br>Eficiencia y ahorro.</h1>
						<div class="col-xs-12 text-center">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-12 nopadding slide slideExperiencia" style="background-image: url('assets/img/img_3.jpg');">
		<div class="vertical backDark"></div>
		<div class="vertical backImage" data-animation="fadeInDownBig" data-delay="0.5s" style="background-image: url('assets/img/img_4.svg');"></div>
		<div class="vertical">
			<div class="container">
				<div class="row text-center">
					<div class="col-xs-12 nopadding">
						<div class="col-xs-12 col-sm-5 nopadding text-center">
							<div class="col-xs-8 col-sm-12 nopadding centered text-left">
								<div class="col-xs-12 noHorizontalPadding vxpadding text-center">
									<img src="assets/img/img_5.png" alt="" class="col-xs-12 centered" data-animation="fadeInRight" data-delay="1s" style="width: 100px;">
								</div>
								<h2 class="extra-bold vpadding textWhite lined text-center-xs" data-animation="fadeInRight" data-delay="1s">5 años de experiencia brindando soluciones en tecnología LED</h2>
						<div class="col-xs-12 text-center">
							<a href="productos" class="btn1" data-animation="fadeInRight" data-delay="1s">COTIZAR</a>
						</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section id="Productos">
	<div class="vertical backImage revealBack" style="background-image: url('assets/img/img_21.svg');"></div>
		<div class="container">
			<div class="row text-center">
				<div class="col-xs-12 nopadding">
					<ul class="linea">
					<?php
						$counter=0;
						while($result = mysql_fetch_assoc($lineas)) {
							$active = ($counter==0) ? 'active' : '';
							$IdLinea=$result['IdLinea'];
							$Linea=utf8_encode ($result['Etiqueta']);
 					?>
					<li>
						<a href="<?=$counter;?>" class="<?=$active;?>"><?=$Linea;?></a>
					</li>
 					<?php
 							$counter++;
 						}
 					?>
					</ul>
				</div>
				<div class="col-xs-12 nopadding">
					<div class="col-xs-12 vxpadding nopadding tabsGeneral">
					<?php
						$IdLinea='';
						$arrayLineas = array();
						$arraySublineas = array();
						$counter=0;
						$counter2=0;
						while($result = mysql_fetch_assoc($sublineas)) {
							$arraySublineas[$counter]['IdSubLinea']=$result['IdSubLinea'];
							$arraySublineas[$counter]['IdLinea']=$result['IdLinea'];
							$arraySublineas[$counter]['Etiqueta']=$result['Etiqueta'];
							if ($IdLinea!=$result['IdLinea']) {
								$arrayLineas[$counter2]=$result['IdLinea'];
								$counter2++;
							}
							$IdLinea=$result['IdLinea'];
							$counter++;
						}
 					?>
					<?php 
					$firstActive=0;
					foreach ($arrayLineas as $key => $value): ?>
						<div class="col-xs-12 nopadding item">
						<?php foreach ($arraySublineas as $keyTwo => $valueTwo): ?>
							<?php if ($arrayLineas[$key]==$arraySublineas[$keyTwo]['IdLinea']): 
								$firstElement = ($firstActive==0) ? "firstElement":"";
							?>
								<div class="col-xs-12 nopadding subItem text-center">
									<a href="<?=$arraySublineas[$keyTwo]['IdSubLinea'];?>" class="col-xs-12 nopadding centered <?=$firstElement;?>">
										<div class="col-xs-12 nopadding img">
											<img src="Admin/assets/img/Sublineas/<?=$arraySublineas[$keyTwo]['IdSubLinea'];?>/img.png" alt="">
										</div>
										<div class="col-xs-12 nopadding text-center">
											<span><?=$arraySublineas[$keyTwo]['Etiqueta'];?></span>
										</div>
									</a>
								</div>
							<?php 
							$firstActive++;
							endif ?>
						<?php endforeach ?>
						</div>
					<?php endforeach ?>

					</div>
					<div class="vertical arrows">
						<div class="col-xs-12 nopadding">
							<a href="#" class="next">
								<img src="assets/img/next.svg" alt="">
							</a>
							<a href="#" class="prev">
								<img src="assets/img/prev.svg" alt="">
							</a>
						</div>
					</div>
				</div>
				<div class="col-xs-12 nopadding productos" id="containerProductos">
					
				</div>
			</div>
		</div>
</section>